import {growthKeys,growthTabs,growthTiers,mountGrowthGroups,mountGrowthSource,normalizeGrowthState,growthRows,growthValues,growthTotal,growthEffectiveTotal,growthSortContext,sortGrowthRows,growthBaseline,growthCellStyle} from './growth-comparison.mjs';
import {statLabels} from './locales/labels.mjs';
import {localized} from './locales/index.mjs';
import {escapeHtml as esc} from './core.mjs';
import {pagePath,stateQuery} from './routing.mjs';
const tierLabels={Unique:{ko:'기본직',en:'Base'},Beginner:{ko:'초급직',en:'Beginner'},Specialty:{ko:'중급직',en:'Specialty'},Intermediate:{ko:'중급직',en:'Specialty'},Advanced:{ko:'상급직',en:'Advanced'},Master:{ko:'최상급직',en:'Master'},Divine:{ko:'신장직',en:'Divine'}};
export function growthComparison(input,{entries,sources,t,lang,base}){
 const state={...input,...normalizeGrowthState(input)},tab=state.growthTab,allRows=growthRows(entries),all=allRows.filter(r=>r.type===tab),stats=growthBaseline(all,state),relative=tab==='character';
 const groupName=r=>localized(tab==='class'?tierLabels[r.group.en]||r.group:r.group,lang),name=r=>r.name[lang];
 const list=sortGrowthRows(all.filter(r=>!state.growthGroup||r.group.en===state.growthGroup),state,lang),{sort,direction}=growthSortContext(state);
 const number=(v,mean=false)=>!Number.isFinite(v)?'—':mean?v.toFixed(1):relative?`${v}%`:`${v>0?'+':''}${v}`;
 const href=id=>pagePath({id},lang,base),currentUrl=pagePath(state,lang,base)+stateQuery(state);
 const groups=[...new Set(all.map(r=>r.group.en))].sort((a,b)=>tab==='class'?(growthTiers[a]??99)-(growthTiers[b]??99):0);
 const tabs=growthTabs.map(kind=>{const next={...state,growthTab:kind,growthGroup:'',growthSort:'default',growthDirection:'desc',growthFocus:''},count=allRows.filter(r=>r.type===kind).length;return `<a id="tab-${kind}" role="tab" href="${esc(pagePath(next,lang,base)+stateQuery(next))}" data-growth-tab="${kind}" aria-selected="${tab===kind}" aria-controls="growth-panel" tabindex="${tab===kind?0:-1}">${t('growth.'+kind)}<small>${count}</small></a>`;}).join('');
 const sortHeader=(key,title,className='')=>`<th scope="col" class="${className}" aria-sort="${sort===key?(direction==='asc'?'ascending':'descending'):'none'}"><button type="button" data-growth-sort="${key}">${title}${sort===key?(direction==='asc'?' ↑':' ↓'):''}</button></th>`;
 const headers=sortHeader('name',t('growth.name'),'name-title')+statLabels.map(([key,ko,en])=>sortHeader(key,lang==='ko'?ko:en)).join('')+sortHeader('total',t('growth.sum'),'total-title')+(relative?`<th scope="col" class="effective-title" aria-sort="${sort==='effective'?(direction==='asc'?'ascending':'descending'):'none'}"><div class="effective-header"><button type="button" data-growth-sort="effective" aria-describedby="effective-help-text">${t('growth.effective')}${sort==='effective'?(direction==='asc'?' ↑':' ↓'):''}</button><details class="header-help"><summary aria-label="${esc(t('growth.effectiveHelpLabel'))}" title="${esc(t('growth.effectiveHelp'))}">?</summary><div id="effective-help-text" role="note">${esc(t('growth.effectiveHelp'))}</div></details></div></th>`:'');
 const meanTotal=growthKeys.every(k=>stats[k].n===all.length)?growthKeys.reduce((sum,k)=>sum+stats[k].mean,0):null,effectiveTotals=all.map(r=>growthEffectiveTotal(r,state)).filter(Number.isFinite),meanEffective=effectiveTotals.length?effectiveTotals.reduce((sum,v)=>sum+v,0)/effectiveTotals.length:null;
 const average=relative?`<tr class="average"><th scope="row">${t('growth.average')}</th>${growthKeys.map(k=>`<td title="n=${stats[k].n}">${number(stats[k].mean,true)}</td>`).join('')}<td>${number(meanTotal,true)}</td><td>${number(meanEffective,true)}</td></tr>`:'';
 const body=list.map(r=>{const label=relative&&r.modified?t(state.growthSkill?'growth.corrected':'growth.base'):groupName(r),values=growthValues(r,state);return `<tr id="growth-row-${esc(r.id)}" data-growth-row="${esc(r.id)}"${r.id===state.growthFocus?' class="growth-focused" aria-current="true"':''}><th scope="row"><div class="row-name">${r.image?`<img src="${esc(r.image)}" alt="" width="24" height="30" loading="lazy" decoding="async">`:''}<div class="row-label">${r.hasDetail?`<a href="${esc(href(r.id))}">${esc(name(r))}</a>`:`<span class="entry-name">${esc(name(r))}</span>`}<small>${esc(label)}</small></div></div></th>${growthKeys.map((k,i)=>{const v=values[k],tooltip=(lang==='ko'?statLabels[i][1]:statLabels[i][2])+': '+number(v)+(relative&&Number.isFinite(v)&&stats[k].mean!=null?' · '+t('growth.average')+' '+stats[k].mean.toFixed(1):'');return `<td class="${Number.isFinite(v)?'':'unknown'}" style="${growthCellStyle(v,k,stats,state)}" title="${esc(tooltip)}">${number(v)}</td>`;}).join('')}<td>${growthTotal(r,state)??'—'}</td>${relative?`<td>${growthEffectiveTotal(r,state)??'—'}</td>`:''}</tr>`;}).join('');
 const usedSources={...sources,'dc-753281':mountGrowthSource},siteGroups=new Map();
 for(const id of new Set(all.map(r=>r.sourceId))){const source=usedSources[id];if(!source)continue;const site=new URL(source.url).hostname;siteGroups.set(site,[...(siteGroups.get(site)||[]),id]);}
 const siteOrder=['game8.jp','game8.co','serenesforest.net','edricsn.com'],siteNames={'game8.jp':'Game8 (JP)','game8.co':'Game8 (EN)','serenesforest.net':'Serenes Forest','cass07.github.io':'Cass07','gall.dcinside.com':lang==='ko'?'디시인사이드':'DC Inside','edricsn.com':lang==='ko'?'에드릭슨':'Edricson'};
 const sourceHtml=[...siteGroups].sort(([a],[b])=>(siteOrder.includes(a)?siteOrder.indexOf(a):siteOrder.length)-(siteOrder.includes(b)?siteOrder.indexOf(b):siteOrder.length)).map(([site,ids])=>`<section class="growth-source-site"><h3>${esc(siteNames[site]||site)}</h3><ul class="growth-source-links">${ids.map(id=>{const source=usedSources[id],covered=all.filter(r=>r.sourceId===id),label=covered.length===1?name(covered[0]):t('growth.reference'+tab[0].toUpperCase()+tab.slice(1));return `<li><a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a></li>`;}).join('')}</ul></section>`).join('');
 const imageRows=all.filter(r=>r.imageSource),imageSources=imageRows.length?`<details class="growth-image-sources"><summary>${t('growth.imageSources')}</summary><p>${imageRows.map(r=>`<a href="${esc(r.imageSource)}" target="_blank" rel="noopener noreferrer" title="${esc(r.imageCredit)}">${esc(name(r))}</a>`).join(', ')}</p></details>`:'';
 return `<div class="growth-comparison" data-growth-comparison><div class="growth-heading"><h1>${t('growth.title')}</h1><p>${t('growth.description')}</p></div><div class="growth-workspace"><div class="growth-tab-wrap item-listing"><div class="growth-tabs item-filter-row" role="tablist" aria-label="${esc(t('growth.tabLabel'))}">${tabs}</div></div><div class="growth-toolbar"><label class="growth-filter" id="group-control"${relative?' hidden':''}><span>${t(tab==='class'?'growth.tier':'growth.kind')}</span><select id="growth-group">${`<option value="">${t('growth.all')}</option>`+groups.map(g=>`<option value="${esc(g)}"${g===state.growthGroup?' selected':''}>${esc(groupName(all.find(r=>r.group.en===g)))}</option>`).join('')}</select></label><label id="skill-control"${relative?'':' hidden'} title="${esc(t('growth.skill'))}"><input id="personal-skill" type="checkbox" aria-label="${esc(t('growth.skill'))}"${state.growthSkill?' checked':''}><span>${t('growth.compactSkill')}</span></label><label class="heat-toggle"><input id="heat-enabled" type="checkbox"${state.growthHeat==='on'?' checked':''}><span>${t('growth.heatmap')}</span></label></div></div><section id="growth-panel" role="tabpanel" aria-labelledby="tab-${tab}"><div class="growth-sheet-meta"><div class="growth-context"><strong>${t('growth.context'+tab[0].toUpperCase()+tab.slice(1))}</strong><span>${t(relative?'growth.unitCharacter':'growth.unitModifier')}</span></div><div class="growth-meta-right"><output id="row-count" aria-live="polite">${t(list.length===all.length?'growth.count':'growth.filteredCount',{count:list.length,total:all.length})}</output><div class="growth-legend"><span>${t(state.growthHeat==='off'?'growth.numeric':relative?'growth.low':'growth.signedLow')}</span>${state.growthHeat==='on'?`<span class="legend-scale" aria-hidden="true"></span><span>${t(relative?'growth.center':'growth.zero')}</span><span>${t(relative?'growth.high':'growth.signedHigh')}</span>`:''}</div></div></div><p class="scroll-help">${t('growth.scroll')}</p><div class="growth-scroll" tabindex="0" role="region" aria-label="${esc(t('growth.tableLabel'))}"><table id="growth-table" class="${relative?'character-table':''}"><caption class="sr-only">${t('growth.title')}</caption><thead><tr>${headers}</tr></thead><tbody id="growth-body">${average+body}</tbody></table></div>${list.length?'':`<p class="growth-empty">${t('growth.empty')}</p>`}<p class="growth-footer-note"><a href="${esc(currentUrl)}#growth-sources">${t('growth.sourcesTitle')}</a></p><details class="growth-method"><summary>${t('growth.methodTitle')}</summary>${(relative?['relativeMethod','stableMethod','totalMethod','effectiveHelp','skillMethod']:['modifierMethod','totalMethod']).map(key=>`<p>${t('growth.'+key)}</p>`).join('')}</details><details class="growth-sources" id="growth-sources"><summary>${t('growth.sourcesTitle')}</summary><p>${t(tab==='mount'?'growth.mountSourceNote':'growth.sourceNote')}</p>${sourceHtml+imageSources}</details></section></div>`;
}
