// Generated by scripts/build-item-icons.py. See docs/ITEM_TYPES.md.
export const itemMedia={
  "sword": {
    "src": "./assets/item-types/sword.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "spear": {
    "src": "./assets/item-types/spear.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "axe": {
    "src": "./assets/item-types/axe.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "bow": {
    "src": "./assets/item-types/bow.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "gauntlet": {
    "src": "./assets/item-types/gauntlet.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "black-magic": {
    "src": "./assets/item-types/black-magic.png",
    "originalUrl": "https://img.game8.co/4613378/1ea1604da2f60ccbc68cae54b5899b09.png/show",
    "sourceUrl": "https://game8.co/games/Fire-Emblem-Fortunes-Weave/archives/621078",
    "credit": "Game8 · Nintendo / INTELLIGENT SYSTEMS",
    "sourceAlt": "Black Magic Icon",
    "sourceSection": "All Weapons and Spells by Type"
  },
  "white-magic": {
    "src": "./assets/item-types/white-magic.png",
    "width": 34,
    "height": 35,
    "originalWidth": 34,
    "originalHeight": 35,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "dark-magic": {
    "src": "./assets/item-types/dark-magic.png",
    "originalUrl": "https://img.game8.co/4613378/1ea1604da2f60ccbc68cae54b5899b09.png/show",
    "sourceUrl": "https://game8.co/games/Fire-Emblem-Fortunes-Weave/archives/621078",
    "credit": "Game8 · Nintendo / INTELLIGENT SYSTEMS",
    "sourceAlt": "Black Magic Icon",
    "sourceSection": "All Weapons and Spells by Type",
    "mappingNote": "No dedicated dark magic icon in the specified section; uses Black Magic Icon."
  },
  "consumable": {
    "src": "./assets/item-types/consumable.png",
    "width": 34,
    "height": 34,
    "originalWidth": 34,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "manual": {
    "src": "./assets/item-types/manual.png",
    "originalUrl": "https://img.game8.co/4613672/e689cf158e0507ab1fa951af5aadb4fc.png/show",
    "sourceUrl": "https://game8.co/games/Fire-Emblem-Fortunes-Weave/archives/621281",
    "credit": "Game8 · Nintendo / INTELLIGENT SYSTEMS",
    "sourceAlt": "Consumables",
    "sourceSection": "List of All Items",
    "mappingNote": "Uses the parent Consumables category icon."
  },
  "gift": {
    "src": "./assets/item-types/gift.png",
    "originalUrl": "https://img.game8.co/4613653/8eab8b1c6a62bf530f0e298327237b6c.png/show",
    "sourceUrl": "https://game8.co/games/Fire-Emblem-Fortunes-Weave/archives/621281",
    "credit": "Game8 · Nintendo / INTELLIGENT SYSTEMS",
    "sourceAlt": "Gifts",
    "sourceSection": "List of All Items"
  },
  "plant": {
    "src": "./assets/item-types/plant.png",
    "width": 29,
    "height": 31,
    "originalWidth": 29,
    "originalHeight": 31,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "meat": {
    "src": "./assets/item-types/meat.png",
    "width": 29,
    "height": 31,
    "originalWidth": 29,
    "originalHeight": 31,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop",
    "mappingNote": "Retains the existing parent ingredient icon mapping; no meat-specific glyph was confirmed."
  },
  "fish": {
    "src": "./assets/item-types/fish.png",
    "width": 29,
    "height": 31,
    "originalWidth": 29,
    "originalHeight": 31,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "ore": {
    "src": "./assets/item-types/ore.png",
    "width": 29,
    "height": 31,
    "originalWidth": 29,
    "originalHeight": 31,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "other": {
    "src": "./assets/item-types/other.png",
    "width": 29,
    "height": 31,
    "originalWidth": 29,
    "originalHeight": 31,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop",
    "mappingNote": "Uses the observed unidentified-container glyph as a representative miscellaneous icon; not an item-specific depiction."
  },
  "accessory": {
    "src": "./assets/item-types/accessory.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "shield": {
    "src": "./assets/item-types/shield.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "promotion": {
    "src": "./assets/item-types/promotion.png",
    "originalUrl": "https://img.game8.co/4613538/00c87999cfe73bea282c8943a7d85e6f.png/show",
    "sourceUrl": "https://game8.co/games/Fire-Emblem-Fortunes-Weave/archives/621281",
    "credit": "Game8 · Nintendo / INTELLIGENT SYSTEMS",
    "sourceAlt": "Exam Licenses",
    "sourceSection": "List of All Items"
  },
  "cursed-sword": {
    "src": "./assets/item-types/cursed-sword.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "cursed-spear": {
    "src": "./assets/item-types/cursed-spear.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "cursed-axe": {
    "src": "./assets/item-types/cursed-axe.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  },
  "cursed-bow": {
    "src": "./assets/item-types/cursed-bow.png",
    "width": 33,
    "height": 34,
    "originalWidth": 33,
    "originalHeight": 34,
    "sourceUrl": "./evidence/item-icons.html",
    "credit": {
      "ko": "관리자 · Nintendo / INTELLIGENT SYSTEMS",
      "en": "administrator · Nintendo / INTELLIGENT SYSTEMS"
    },
    "checked": "2026-10-07",
    "method": "administrator-gameplay-crop"
  }
};
