// Source-discovered images. See docs/IMAGES.md.
export const media = {
  "part1-map": {
    "src": "./assets/part1-map/overview.webp",
    "width": 500,
    "height": 469,
    "originalWidth": 810,
    "originalHeight": 760,
    "sourceUrl": "./evidence/part1-map.html",
    "credit": "Administrator gameplay captures · Nintendo / INTELLIGENT SYSTEMS",
    "checkedAt": "2026-10-02",
    "rights": "Game artwork belongs to Nintendo / INTELLIGENT SYSTEMS. Source crops only; no independent reuse permission verified."
  },
  "dagda": {
    "credit": "Fortunes Weave Guide / Fire Emblem Wiki · Nintendo / INTELLIGENT SYSTEMS",
    "rights": "Source labels this personal, non-commercial fair-use reference, not CC BY-SA; no independent permission verified.",
    "sourceUrl": "https://fortunesweave.co.uk/map",
    "src": "./assets/dagda.webp",
    "checkedAt": "2026-09-25",
    "originalUrl": "https://fortunesweave.co.uk/images/world-map/dagda.webp",
    "originalWidth": 3458,
    "originalHeight": 2442,
    "width": 500,
    "height": 353
  },
  "eshmel": {
    "src": "./assets/portraits/eshmel.png",
    "originalUrl": "https://cdn.fireemblemwiki.org/f/f0/FEFW_Eshmel.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Eshmel.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 498,
    "height": 500,
    "thumbnailSrc": "./assets/portraits/eshmel-list.webp",
    "originalWidth": 3527,
    "originalHeight": 3543
  },
  "hong-hua": {
    "src": "./assets/portraits/hong-hua.png",
    "thumbnailSrc": "./assets/portraits/hong-hua-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/12/FEFW_Hong_Hua_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Hong_Hua_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 480,
    "height": 500,
    "originalWidth": 3453,
    "originalHeight": 3599
  },
  "troy": {
    "src": "./assets/portraits/troy.png",
    "thumbnailSrc": "./assets/portraits/troy-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/4e/FEFW_Troy_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Troy_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 475,
    "height": 500,
    "originalWidth": 3389,
    "originalHeight": 3571
  },
  "cai": {
    "src": "./assets/portraits/cai.png",
    "originalUrl": "https://cdn.fireemblemwiki.org/6/66/FEFW_Cai.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Cai.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 488,
    "thumbnailSrc": "./assets/portraits/cai-list.webp",
    "originalWidth": 1546,
    "originalHeight": 1510
  },
  "tialla": {
    "src": "./assets/portraits/tialla.png",
    "thumbnailSrc": "./assets/portraits/tialla-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/1f/FEFW_Tialla_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Tialla_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 420,
    "height": 500,
    "originalWidth": 818,
    "originalHeight": 974
  },
  "peter": {
    "src": "./assets/portraits/peter.png",
    "thumbnailSrc": "./assets/portraits/peter-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/b/b4/FEFW_Peter_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Peter_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 344,
    "height": 500,
    "originalWidth": 2565,
    "originalHeight": 3727
  },
  "castor": {
    "src": "./assets/portraits/castor.png",
    "thumbnailSrc": "./assets/portraits/castor-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/5/58/FE18_Castor.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FE18_Castor.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 472,
    "height": 500,
    "originalWidth": 528,
    "originalHeight": 559
  },
  "ultand": {
    "src": "./assets/portraits/ultand.png",
    "thumbnailSrc": "./assets/portraits/ultand-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/27/FEFW_Ultand_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Ultand_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 477,
    "originalWidth": 1022,
    "originalHeight": 974
  },
  "dietrich": {
    "src": "./assets/portraits/dietrich.png",
    "originalUrl": "https://cdn.fireemblemwiki.org/b/bf/FEFW_Dietrich.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Dietrich.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 483,
    "thumbnailSrc": "./assets/portraits/dietrich-list.webp",
    "originalWidth": 1774,
    "originalHeight": 1712
  },
  "fabio": {
    "src": "./assets/portraits/fabio.png",
    "thumbnailSrc": "./assets/portraits/fabio-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/1c/FEFW_Fabio_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Fabio_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3087,
    "originalHeight": 3085
  },
  "esmeralda": {
    "src": "./assets/portraits/esmeralda.png",
    "thumbnailSrc": "./assets/portraits/esmeralda-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/b/b7/FEFW_Esmeralda_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Esmeralda_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 499,
    "height": 500,
    "originalWidth": 3102,
    "originalHeight": 3109
  },
  "mikaela": {
    "src": "./assets/portraits/mikaela.png",
    "thumbnailSrc": "./assets/portraits/mikaela-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/8/8e/FEFW_Mikaela_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Mikaela_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 474,
    "originalWidth": 1042,
    "originalHeight": 988
  },
  "theodora": {
    "src": "./assets/portraits/theodora.png",
    "originalUrl": "https://cdn.fireemblemwiki.org/8/82/FEFW_Theodora.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Theodora.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 498,
    "thumbnailSrc": "./assets/portraits/theodora-list.webp",
    "originalWidth": 1698,
    "originalHeight": 1692
  },
  "bonaventure": {
    "src": "./assets/portraits/bonaventure.png",
    "thumbnailSrc": "./assets/portraits/bonaventure-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/23/FEFW_Bonaventure_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Bonaventure_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 498,
    "height": 500,
    "originalWidth": 996,
    "originalHeight": 1000
  },
  "tobias": {
    "src": "./assets/portraits/tobias.png",
    "thumbnailSrc": "./assets/portraits/tobias-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/0b/FEFW_Tobias_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Tobias_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 468,
    "originalWidth": 1054,
    "originalHeight": 986
  },
  "lysander": {
    "src": "./assets/portraits/lysander.png",
    "thumbnailSrc": "./assets/portraits/lysander-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/05/FEFW_Lysander_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Lysander_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 463,
    "height": 500,
    "originalWidth": 3072,
    "originalHeight": 3317
  },
  "lilian": {
    "src": "./assets/portraits/lilian.png",
    "thumbnailSrc": "./assets/portraits/lilian-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/b/ba/FEFW_Lilian_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Lilian_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 440,
    "height": 500,
    "originalWidth": 858,
    "originalHeight": 976
  },
  "leda": {
    "src": "./assets/portraits/leda.png",
    "originalUrl": "https://cdn.fireemblemwiki.org/e/e0/FEFW_Leda.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Leda.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 309,
    "height": 500,
    "thumbnailSrc": "./assets/portraits/leda-list.webp",
    "originalWidth": 964,
    "originalHeight": 1562
  },
  "buccar": {
    "src": "./assets/portraits/buccar.png",
    "thumbnailSrc": "./assets/portraits/buccar-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/c/c0/FEFW_Buccar_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Buccar_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 416,
    "originalWidth": 1206,
    "originalHeight": 1004
  },
  "sirocco": {
    "src": "./assets/portraits/sirocco.png",
    "thumbnailSrc": "./assets/portraits/sirocco-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/a2/FEFW_Sirocco_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Sirocco_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 485,
    "height": 500,
    "originalWidth": 1002,
    "originalHeight": 1032
  },
  "mu": {
    "src": "./assets/portraits/mu.png",
    "thumbnailSrc": "./assets/portraits/mu-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/98/FEFW_Mu_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Mu_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 306,
    "height": 500,
    "originalWidth": 608,
    "originalHeight": 992
  },
  "olympia": {
    "src": "./assets/portraits/olympia.png",
    "thumbnailSrc": "./assets/portraits/olympia-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/0e/FEFW_Olympia_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Olympia_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 493,
    "height": 500,
    "originalWidth": 992,
    "originalHeight": 1006
  },
  "bertrand": {
    "src": "./assets/portraits/bertrand.png",
    "thumbnailSrc": "./assets/portraits/bertrand-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/72/FEFW_Bertrand_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Bertrand_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 417,
    "height": 500,
    "originalWidth": 880,
    "originalHeight": 1054
  },
  "gaitz": {
    "src": "./assets/portraits/gaitz.png",
    "thumbnailSrc": "./assets/portraits/gaitz-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/99/FEFW_Gaitz_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Gaitz_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 499,
    "height": 500,
    "originalWidth": 3388,
    "originalHeight": 3398
  },
  "goliath": {
    "src": "./assets/portraits/goliath.webp",
    "thumbnailSrc": "./assets/portraits/goliath-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/6/6f/FEFW_Nintendo_Today_Goliath_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Goliath_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "jester": {
    "src": "./assets/portraits/jester.webp",
    "thumbnailSrc": "./assets/portraits/jester-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/99/FEFW_Nintendo_Today_Jester_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Jester_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "dante": {
    "src": "./assets/portraits/dante.png",
    "thumbnailSrc": "./assets/portraits/dante-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/c/c0/FEFW_Dante_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Dante_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 279,
    "height": 500,
    "originalWidth": 2175,
    "originalHeight": 3900
  },
  "talimun": {
    "src": "./assets/portraits/talimun.png",
    "thumbnailSrc": "./assets/portraits/talimun-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/46/FEFW_Talimun_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Talimun_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 456,
    "height": 500,
    "originalWidth": 923,
    "originalHeight": 1012
  },
  "ursula": {
    "src": "./assets/portraits/ursula.png",
    "thumbnailSrc": "./assets/portraits/ursula-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/c/c6/FEFW_Ursula_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Ursula_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 435,
    "height": 500,
    "originalWidth": 3184,
    "originalHeight": 3659
  },
  "simon": {
    "src": "./assets/portraits/simon.webp",
    "thumbnailSrc": "./assets/portraits/simon-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/96/FEFW_Nintendo_Today_Simon_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Simon_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "ludia": {
    "src": "./assets/portraits/ludia.webp",
    "thumbnailSrc": "./assets/portraits/ludia-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/5/55/FEFW_Nintendo_Today_Ludia_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Ludia_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "fianna": {
    "src": "./assets/portraits/fianna.webp",
    "thumbnailSrc": "./assets/portraits/fianna-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/c/c4/FEFW_Nintendo_Today_Fianna_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Fianna_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "orchel": {
    "src": "./assets/portraits/orchel.png",
    "thumbnailSrc": "./assets/portraits/orchel-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/d/da/FEFW_Orchel_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Orchel_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 313,
    "height": 500,
    "originalWidth": 630,
    "originalHeight": 1006
  },
  "diego": {
    "src": "./assets/portraits/diego.png",
    "thumbnailSrc": "./assets/portraits/diego-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/2e/FEFW_Diego_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Diego_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 396,
    "height": 500,
    "originalWidth": 3045,
    "originalHeight": 3844
  },
  "loretta": {
    "src": "./assets/portraits/loretta.png",
    "thumbnailSrc": "./assets/portraits/loretta-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/7c/FEFW_Loretta_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Loretta_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 362,
    "height": 500,
    "originalWidth": 2844,
    "originalHeight": 3923
  },
  "seteth": {
    "src": "./assets/portraits/seteth.png",
    "thumbnailSrc": "./assets/portraits/seteth-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/41/Portrait_seteth_fe18.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Portrait_seteth_fe18.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 206,
    "height": 235
  },
  "ninae": {
    "src": "./assets/portraits/ninae.png",
    "thumbnailSrc": "./assets/portraits/ninae-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/e/ea/FEFW_Ninae_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Ninae_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 461,
    "height": 500,
    "originalWidth": 3329,
    "originalHeight": 3611
  },
  "anatolia": {
    "src": "./assets/portraits/anatolia.png",
    "thumbnailSrc": "./assets/portraits/anatolia-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/13/FEFW_Anatolia_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Anatolia_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 438,
    "height": 500,
    "originalWidth": 859,
    "originalHeight": 980
  },
  "sha-lan": {
    "src": "./assets/portraits/sha-lan.png",
    "thumbnailSrc": "./assets/portraits/sha-lan-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/8/85/FEFW_Sha_Lan_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Sha_Lan_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 394,
    "height": 500,
    "originalWidth": 2971,
    "originalHeight": 3769
  },
  "nezha": {
    "src": "./assets/portraits/nezha.webp",
    "thumbnailSrc": "./assets/portraits/nezha-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/91/FEFW_Nintendo_Today_Nezha_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Nezha_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "dadao": {
    "src": "./assets/portraits/dadao.png",
    "thumbnailSrc": "./assets/portraits/dadao-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/17/FEFW_Dadao_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Dadao_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 475,
    "originalWidth": 3444,
    "originalHeight": 3269
  },
  "halvin": {
    "src": "./assets/portraits/halvin.webp",
    "thumbnailSrc": "./assets/portraits/halvin-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/77/FEFW_Nintendo_Today_Halvin_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Halvin_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "long": {
    "src": "./assets/portraits/long.png",
    "thumbnailSrc": "./assets/portraits/long-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/e/e9/Ss_fe18_portrait_long.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_portrait_long.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 617,
    "originalHeight": 617
  },
  "benditz": {
    "src": "./assets/portraits/benditz.png",
    "thumbnailSrc": "./assets/portraits/benditz-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/72/FEFW_Benditz_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Benditz_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 456,
    "originalWidth": 3608,
    "originalHeight": 3289
  },
  "alexandra": {
    "src": "./assets/portraits/alexandra.png",
    "thumbnailSrc": "./assets/portraits/alexandra-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/8/88/FEFW_Alexandra_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Alexandra_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 476,
    "originalWidth": 1024,
    "originalHeight": 974
  },
  "zarcone": {
    "src": "./assets/portraits/zarcone.webp",
    "thumbnailSrc": "./assets/portraits/zarcone-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/a1/FEFW_Nintendo_Today_Zarcone_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Zarcone_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "jasmine": {
    "src": "./assets/portraits/jasmine.webp",
    "thumbnailSrc": "./assets/portraits/jasmine-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/af/FEFW_Nintendo_Today_Jasmine_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Jasmine_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "kiroc": {
    "src": "./assets/portraits/kiroc.webp",
    "thumbnailSrc": "./assets/portraits/kiroc-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/1b/FEFW_Nintendo_Today_Kiroc_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Kiroc_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "inyoni": {
    "src": "./assets/portraits/inyoni.webp",
    "thumbnailSrc": "./assets/portraits/inyoni-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/76/FEFW_Nintendo_Today_Inyoni_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Inyoni_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "peppe": {
    "src": "./assets/portraits/peppe.webp",
    "thumbnailSrc": "./assets/portraits/peppe-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/e/ea/FEFW_Nintendo_Today_Peppe_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Peppe_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "solel": {
    "src": "./assets/portraits/solel.png",
    "originalUrl": "https://cdn.fireemblemwiki.org/c/c3/FEFW_Solel.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Solel.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 274,
    "height": 500,
    "thumbnailSrc": "./assets/portraits/solel-list.webp",
    "originalWidth": 1052,
    "originalHeight": 1920
  },
  "anna": {
    "src": "./assets/portraits/anna.png",
    "thumbnailSrc": "./assets/portraits/anna-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/03/FEFW_Anna_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Anna_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 400,
    "height": 400
  },
  "aurora": {
    "src": "./assets/portraits/aurora.png",
    "thumbnailSrc": "./assets/portraits/aurora-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/d/da/Ss_fe18_unknown_character_02.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_unknown_character_02.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 718,
    "originalHeight": 718
  },
  "centurio": {
    "src": "./assets/portraits/centurio.png",
    "thumbnailSrc": "./assets/portraits/centurio-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/20/FEFW_Centurio_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Centurio_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 462,
    "originalWidth": 3608,
    "originalHeight": 3331
  },
  "sofia": {
    "src": "./assets/portraits/sofia.png",
    "thumbnailSrc": "./assets/portraits/sofia-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/2c/FEFW_Sofia_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Sofia_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 356,
    "height": 500,
    "originalWidth": 2732,
    "originalHeight": 3842
  },
  "guzran": {
    "src": "./assets/portraits/guzran.png",
    "thumbnailSrc": "./assets/portraits/guzran-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/27/FEFW_Guzran_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Guzran_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 480,
    "originalWidth": 3583,
    "originalHeight": 3443
  },
  "nydine": {
    "src": "./assets/portraits/nydine.png",
    "thumbnailSrc": "./assets/portraits/nydine-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/49/FEFW_Nydine_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nydine_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 497,
    "originalWidth": 3487,
    "originalHeight": 3465
  },
  "io": {
    "src": "./assets/portraits/io.webp",
    "thumbnailSrc": "./assets/portraits/io-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/6/67/FEFW_Nintendo_Today_Io_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Io_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "catania": {
    "src": "./assets/portraits/catania.png",
    "thumbnailSrc": "./assets/portraits/catania-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/98/FEFW_Catania_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Catania_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 416,
    "height": 500,
    "originalWidth": 3222,
    "originalHeight": 3872
  },
  "noctula": {
    "src": "./assets/portraits/noctula.png",
    "thumbnailSrc": "./assets/portraits/noctula-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/02/FEFW_Noctula_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Noctula_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 405,
    "height": 500,
    "originalWidth": 3032,
    "originalHeight": 3744
  },
  "yang-jie": {
    "src": "./assets/portraits/yang-jie.png",
    "thumbnailSrc": "./assets/portraits/yang-jie-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/a6/FEFW_Yang_Jie_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Yang_Jie_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 487,
    "height": 500,
    "originalWidth": 3422,
    "originalHeight": 3513
  },
  "nuzzuo": {
    "src": "./assets/portraits/nuzzuo.png",
    "thumbnailSrc": "./assets/portraits/nuzzuo-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/a3/FEFW_Nuzzuo_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nuzzuo_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 493,
    "originalWidth": 3535,
    "originalHeight": 3488
  },
  "majide": {
    "src": "./assets/portraits/majide.webp",
    "thumbnailSrc": "./assets/portraits/majide-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/4e/FEFW_Nintendo_Today_Majide_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Majide_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "aswan": {
    "src": "./assets/portraits/aswan.png",
    "thumbnailSrc": "./assets/portraits/aswan-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/6/67/Ss_fe18_aswan_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_aswan_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 415,
    "height": 469
  },
  "maria": {
    "src": "./assets/portraits/maria.png",
    "thumbnailSrc": "./assets/portraits/maria-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/75/Ss_fe18_maria_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_maria_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 475,
    "height": 490
  },
  "lind": {
    "src": "./assets/portraits/lind.png",
    "thumbnailSrc": "./assets/portraits/lind-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/03/Ss_fe18_Lind_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_Lind_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 435,
    "height": 484
  },
  "hannibal": {
    "src": "./assets/portraits/hannibal.png",
    "thumbnailSrc": "./assets/portraits/hannibal-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/d/d9/Ss_fe18_crop_hannibal.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_crop_hannibal.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 308,
    "height": 358
  },
  "nathan": {
    "src": "./assets/portraits/nathan.png",
    "thumbnailSrc": "./assets/portraits/nathan-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/a8/FEFW_Nathan_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nathan_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 477,
    "height": 500,
    "originalWidth": 3050,
    "originalHeight": 3198
  },
  "creek": {
    "src": "./assets/portraits/creek.png",
    "thumbnailSrc": "./assets/portraits/creek-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/90/FEFW_Creek_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Creek_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 475,
    "height": 500,
    "originalWidth": 3297,
    "originalHeight": 3473
  },
  "dyan": {
    "src": "./assets/portraits/dyan.png",
    "thumbnailSrc": "./assets/portraits/dyan-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/2d/Portrait_dyan_fe18.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Portrait_dyan_fe18.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 366,
    "height": 384
  },
  "bartolome": {
    "src": "./assets/portraits/bartolome.png",
    "thumbnailSrc": "./assets/portraits/bartolome-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/1b/SS_fe18_bartolome_model_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:SS_fe18_bartolome_model_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 480,
    "height": 500,
    "originalWidth": 1029,
    "originalHeight": 1071
  },
  "bjor": {
    "src": "./assets/portraits/bjor.png",
    "thumbnailSrc": "./assets/portraits/bjor-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/71/Ss_fe18_bjor_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_bjor_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 414,
    "height": 465
  },
  "balboa": {
    "src": "./assets/portraits/balboa.png",
    "thumbnailSrc": "./assets/portraits/balboa-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/5/52/Ss_fe18_balboa_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_balboa_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 457,
    "height": 496
  },
  "lechner": {
    "src": "./assets/portraits/lechner.png",
    "thumbnailSrc": "./assets/portraits/lechner-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/48/Ss_fe18_unknown_character_55.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_unknown_character_55.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 334,
    "height": 347
  },
  "guillermo": {
    "src": "./assets/portraits/guillermo.png",
    "thumbnailSrc": "./assets/portraits/guillermo-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/28/Ss_fe18_guillermo_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_guillermo_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 123,
    "height": 123
  },
  "martila": {
    "src": "./assets/portraits/martila.webp",
    "thumbnailSrc": "./assets/portraits/martila-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/70/FEFW_Nintendo_Today_Maria_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Maria_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 331,
    "height": 500,
    "originalWidth": 2875,
    "originalHeight": 4347
  },
  "sothis": {
    "src": "./assets/portraits/sothis.png",
    "thumbnailSrc": "./assets/portraits/sothis-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/6/66/FEFW_Sothis_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Sothis_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 416,
    "originalWidth": 1160,
    "originalHeight": 964
  },
  "fortuna": {
    "src": "./assets/portraits/fortuna.png",
    "thumbnailSrc": "./assets/portraits/fortuna-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/9/90/FEFW_Fortuna_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Fortuna_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 457,
    "originalWidth": 1184,
    "originalHeight": 1082
  },
  "mars": {
    "src": "./assets/portraits/mars.webp",
    "thumbnailSrc": "./assets/portraits/mars-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/a/a9/FEFW_Nintendo_Today_Mars_profile.webp",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Nintendo_Today_Mars_profile.webp",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 3535,
    "originalHeight": 3535
  },
  "kalla": {
    "src": "./assets/portraits/kalla.png",
    "thumbnailSrc": "./assets/portraits/kalla-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/d/d0/FEFW_Kalla_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FEFW_Kalla_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 495,
    "height": 500,
    "originalWidth": 3418,
    "originalHeight": 3456
  },
  "smyrnos": {
    "src": "./assets/portraits/smyrnos.png",
    "thumbnailSrc": "./assets/portraits/smyrnos-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/01/Ss_fe18_smyrnos_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_smyrnos_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 198,
    "height": 218
  },
  "jurah": {
    "src": "./assets/portraits/jurah.png",
    "thumbnailSrc": "./assets/portraits/jurah-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/0/05/Ss_fe18_jurah_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_jurah_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 444,
    "height": 478
  },
  "credna": {
    "src": "./assets/portraits/credna.png",
    "thumbnailSrc": "./assets/portraits/credna-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/b/b2/Fe18_credna_portrait.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Fe18_credna_portrait.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 176,
    "height": 183
  },
  "poloni": {
    "src": "./assets/portraits/poloni.png",
    "thumbnailSrc": "./assets/portraits/poloni-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/2e/Portrait_berafi_fe18.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Portrait_berafi_fe18.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 390,
    "height": 343
  },
  "gabriel": {
    "src": "./assets/portraits/gabriel.png",
    "thumbnailSrc": "./assets/portraits/gabriel-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/c/ce/Ss_fe18_gabriel_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_gabriel_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 438,
    "height": 357
  },
  "nomved": {
    "src": "./assets/portraits/nomved.png",
    "thumbnailSrc": "./assets/portraits/nomved-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/19/Ss_fe18_nomved_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_nomved_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 466,
    "height": 466
  },
  "mahadu": {
    "src": "./assets/portraits/mahadu.png",
    "thumbnailSrc": "./assets/portraits/mahadu-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/7b/FE18_Mahadu.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:FE18_Mahadu.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 302,
    "height": 289
  },
  "kumos": {
    "src": "./assets/portraits/kumos.png",
    "thumbnailSrc": "./assets/portraits/kumos-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/7/73/Ss_fe18_kumos_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_kumos_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 472,
    "height": 462
  },
  "raksha": {
    "src": "./assets/portraits/raksha.png",
    "thumbnailSrc": "./assets/portraits/raksha-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/4/43/Ss_fe18_raksha_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_raksha_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 468,
    "height": 481
  },
  "iliana": {
    "src": "./assets/portraits/iliana.png",
    "thumbnailSrc": "./assets/portraits/iliana-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/f/f3/Ss_fe18_iliana_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_iliana_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 499,
    "originalWidth": 510,
    "originalHeight": 509
  },
  "baozi": {
    "src": "./assets/portraits/baozi.png",
    "thumbnailSrc": "./assets/portraits/baozi-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/2/26/Ss_fe18_baozi_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_baozi_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 421,
    "height": 444
  },
  "shenlo": {
    "src": "./assets/portraits/shenlo.png",
    "thumbnailSrc": "./assets/portraits/shenlo-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/5/57/Ss_fe18_shenlo_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_shenlo_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 375,
    "height": 500,
    "originalWidth": 449,
    "originalHeight": 599
  },
  "yanjin": {
    "src": "./assets/portraits/yanjin.png",
    "thumbnailSrc": "./assets/portraits/yanjin-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/5/54/Ss_fe18_yanjin_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_yanjin_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 250,
    "height": 250
  },
  "cruaidin": {
    "src": "./assets/portraits/cruaidin.png",
    "thumbnailSrc": "./assets/portraits/cruaidin-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/8/83/Ss_fe18_cruadin_portrait_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_cruadin_portrait_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 448,
    "height": 500,
    "originalWidth": 645,
    "originalHeight": 720
  },
  "bahr-vahn": {
    "src": "./assets/portraits/bahr-vahn.png",
    "thumbnailSrc": "./assets/portraits/bahr-vahn-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/1/1b/SS_fe18_bartolome_model_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:SS_fe18_bartolome_model_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 480,
    "height": 500,
    "originalWidth": 1029,
    "originalHeight": 1071
  },
  "gilchris": {
    "src": "./assets/portraits/gilchris.png",
    "thumbnailSrc": "./assets/portraits/gilchris-list.webp",
    "originalUrl": "https://cdn.fireemblemwiki.org/d/db/Ss_fe18_gilchris_crop.png",
    "sourceUrl": "https://fireemblemwiki.org/wiki/File:Ss_fe18_gilchris_crop.png",
    "credit": "Nintendo / INTELLIGENT SYSTEMS · Fire Emblem Wiki",
    "checkedAt": "2026-09-26",
    "rights": "Game artwork; no open redistribution licence verified.",
    "width": 500,
    "height": 500,
    "originalWidth": 788,
    "originalHeight": 788
  }
};
